### ISSUE TITLE
Website Not Working

### ISSUE THREAD

**Issue by jeffstjean** [BallAerospace/cosmos-website#41]
Hi I believe 91cb27e2cb60dd516bae55b4eaf70d110b8f4d81 caused the Github pages to no longer be live. I get a 404 when trying to access [https://ballaerospace.github.io/docs/v5/](https://ballaerospace.github.io/docs/v5/)

**Comment by dlackner** [comment]
I am having the same issue. Website no longer works. 404 error when trying to access.

![Screenshot from 2022-06-30 13-41-34](https://user-images.githubusercontent.com/23264976/176774694-04070eb0-db3e-4650-9440-68e55a814249.png)

**Comment by ryanatball** [comment]
Sorry guys, this was the process of me moving the site back to the default domain:
https://ballaerospace.github.io/cosmos-website/

cosmosrb.com and cosmosc2.com should be setup to redirect there at least until the end of July.

**Comment by dlackner** [comment]
Thanks Ryan! Works.
